[11.0] [ADD] mdc_workstation_cards_employee_rel
solvosci/manufacture pull request #10
Opened 2021-05-25 16:35 UTC by lmiguens-solvos

Add employee to workstation cards.
To able to put employee in a workstation card.
And when a employee changes his workstation then changes the workstation of all workstation cards  of this employee with the new workstation of the employee.

2021-05-25 17:35 UTC, dalonsod requested changes
Functional and code review, tested:
- Unset the employee of a workstation => workstation cards of the employee are workstation unset, but remains with the employee (OK)
- Set a unassigned workstation to this employee => the workstation cards of the employee are properly reassigned to the new workstation (OK).
- Make the same operations, but making an employee substitution => the workstation cards of the remained assigned employee are re-assigned, and the original employee are unassigned (OK).
- Emulating input and output, no problems detected (attending https://github.com/solvosci/manufacture/blob/8732facc8e95aa9e79f3e89d5ee3e03a147eb0a7/mdc/models/chkpointdata.py#L317) (OK)

Anyway, I have one doubt:
- if an employee is unassigned from a workstation, their workstation cards will be still assigned to him, permanently. Is there any situation that we'd interested in completely unassign them? If needed, then we should provide a server action for "massive unassign workstation cards only assigned to an employee" to unset them, or the user should make this work one by one. What do you think?

2021-05-25 17:35 UTC, dalonsod commented on mdc_workstation_cards_employee_rel/hooks.py
> +                    })
This also should work (https://www.odoo.com/documentation/11.0/reference/orm.html#odoo.models.Model.write):
```suggestion
                workstation_cards.write({
                    'employee_id': reg.current_employee_id.id
                })
```

2021-05-25 17:35 UTC, dalonsod commented on mdc_workstation_cards_employee_rel/models/structure.py
> +        if 'current_employee_id' in values and values['current_employee_id']:
Code suggestion:
```suggestion
        if values.get('current_employee_id', False):
```

2021-05-25 17:35 UTC, dalonsod commented on mdc_workstation_cards_employee_rel/models/structure.py
> +                    })
Suggested:
```suggestion
                old_employee_cards.write({
                    'workstation_id': False
                })
```

2021-05-25 17:35 UTC, dalonsod commented on mdc_workstation_cards_employee_rel/models/structure.py
> +                    })
Suggested:
```suggestion
                new_employee_cards.write({
                    'workstation_id': self.id
                })
```

2021-05-26 11:44 UTC, lmiguens-solvos commented
> Functional and code review, tested:
> 
> * Unset the employee of a workstation => workstation cards of the employee are workstation unset, but remains with the employee (OK)
> * Set a unassigned workstation to this employee => the workstation cards of the employee are properly reassigned to the new workstation (OK).
> * Make the same operations, but making an employee substitution => the workstation cards of the remained assigned employee are re-assigned, and the original employee are unassigned (OK).
> * Emulating input and output, no problems detected (attending https://github.com/solvosci/manufacture/blob/8732facc8e95aa9e79f3e89d5ee3e03a147eb0a7/mdc/models/chkpointdata.py#L317
>   ) (OK)
> 
> Anyway, I have one doubt:
> 
> * if an employee is unassigned from a workstation, their workstation cards will be still assigned to him, permanently. Is there any situation that we'd interested in completely unassign them? If needed, then we should provide a server action for "massive unassign workstation cards only assigned to an employee" to unset them, or the user should make this work one by one. What do you think?

Thanks for writing all the OK tests.

About the doubt, I understand that there may be cases in which they need to change some data (employee or position) of cards in a massive way, and that it would be good to have a massive server action, but that improvement I understand that it is not included in this budget. If in next days or months, it is necessary, it can still be attacked in the remaining hours of the bag or if this bag of hours increases.

2021-05-26 11:48 UTC, lmiguens-solvos commented on mdc_workstation_cards_employee_rel/hooks.py
> +                    })
Yes, I know it. But in this case, in this model, the write method has a self.ensure_one(). Then that improvement does not work. 
https://github.com/solvosci/manufacture/blob/439c0843f25dbea63d6cddf7e7a0f9aa2842c4f4/mdc/models/structure.py#L253

2021-05-26 11:50 UTC, lmiguens-solvos commented on mdc_workstation_cards_employee_rel/models/structure.py
> +        if 'current_employee_id' in values and values['current_employee_id']:
ok, I'll do it

2021-05-26 11:51 UTC, lmiguens-solvos commented on mdc_workstation_cards_employee_rel/models/structure.py
> +                    })
As i said before, in this model, the write method has a self.ensure_one()

2021-05-26 11:51 UTC, lmiguens-solvos commented on mdc_workstation_cards_employee_rel/models/structure.py
> +                    })
As i said before, in this model, the write method has a self.ensure_one()

2021-05-26 11:51 UTC, dalonsod commented on mdc_workstation_cards_employee_rel/hooks.py
> +                    })
Oopps I didn't see it

2021-05-26 14:18 UTC, closed without merging