[ADD] mdc_rpt_physical_worksheet
solvosci/manufacture pull request #2
Opened 2020-04-23 09:06 UTC by lmiguens-solvos

Adds Report Physical Worksheet with data:
            - employee
            - workstation
            - date
            - total hours day
            - times in and times out of the day

2020-04-23 11:27 UTC, dalonsod requested changes
See comments
Pending physical vs massive worksheet marks.

2020-04-23 11:27 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report.py
> +    worksheet_type = fields.Char('Worksheet Type', readonly=True)
A `Selection` field with two possible values fits perfectly, what do you think?

2020-04-23 11:27 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report_views.xml
> +                    <field name="shift_code"/>
Missing useful search fields: `worksheet_date` and `worksheet_type`

2020-04-23 11:27 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report_views.xml
> +                    <filter name="today" string="Today" domain="[('worksheet_date', '&gt;=', current_date)]"/>
Missing useful predefined filters (within a `separator`): worksheet input & output

2020-04-23 11:27 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report_views.xml
> +                        <filter string="Shift Code" name="groupby_shift" domain="[]" context="{'group_by':'shift_code'}"/>
A `worksheet_date` group should be useful, but I'm not sure

2020-04-23 11:27 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report_xlsx.py
> +def formats():
Is it possible to reuse `formats` function already defined in `mdc` addon?

2020-04-23 11:27 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report_xlsx.py
> +        return local_dt
Need to review, I'll take a look:

> `context_tz = pytz.timezone(self.env.context.get('tz') or self.env.user.tz or 'Europe/Madrid')`

I don't know if environment will always provide the timezone; the user usually has it undefined. So, the last option should be a module configuration parameter (such as "Pyshical worksheet report Default timezone").

> `diffH = int(str(dt_local)[19:22])`

This is the weakest point of the code, I'll made some tests or look for an alternative

2020-04-23 14:43 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report_xlsx.py
> +        return local_dt
Tested, these are my conclusions:
- Algorithm to adapt timezone seems ok in general.
- `self.env.context.get('tz')` actually gets the same value than `self.env.user.tz`, and can be both `False`. So, a general parameter configuration is mandatory.
- The current code should fail in two situations: (1) since the timezone adaptations are only applied to time value, sometimes the date value could be wrong (e.g. a worksheet around midnight), and (2) less important, the hour offset should include 1/2 hour fragments, e.g. India +05:30 XD

I'd develop the general configuration parameter, @lmiguens-solvos could you fix (1)?

2020-04-23 16:08 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report_xlsx.py
> +        return local_dt
Finally I found an alternative and clearer code. Could you check?

```suggestion
    def convert_UTC_to_TZ(self, utc_dt):
        context_tz = pytz.timezone(self.env.context.get('tz') or self.env.user.tz or 'Europe/Madrid')
        return utc_dt + datetime.timedelta(seconds=context_tz.utcoffset(utc_dt).total_seconds())
```

2020-04-24 11:57 UTC, lmiguens-solvos commented on mdc_rpt_physical_worksheet/report/report.py
> +    worksheet_type = fields.Char('Worksheet Type', readonly=True)
you're right. I'll change it

2020-04-24 11:57 UTC, lmiguens-solvos commented on mdc_rpt_physical_worksheet/report/report_views.xml
> +                    <field name="shift_code"/>
ok. I'll add them

2020-04-24 11:57 UTC, lmiguens-solvos commented on mdc_rpt_physical_worksheet/report/report_views.xml
> +                    <filter name="today" string="Today" domain="[('worksheet_date', '&gt;=', current_date)]"/>
Ok. I'll add them

2020-04-24 11:57 UTC, lmiguens-solvos commented on mdc_rpt_physical_worksheet/report/report_views.xml
> +                        <filter string="Shift Code" name="groupby_shift" domain="[]" context="{'group_by':'shift_code'}"/>
I'll put it

2020-04-24 11:57 UTC, lmiguens-solvos commented on mdc_rpt_physical_worksheet/report/report_xlsx.py
> +def formats():
I was not capable

2020-04-24 11:57 UTC, lmiguens-solvos commented on mdc_rpt_physical_worksheet/report/report_xlsx.py
> +        return local_dt
It works perfectly

2020-04-24 12:04 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report_xlsx.py
> +def formats():
ok, I'll take a look

2020-04-25 08:44 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report_views.xml
> +                        <filter string="Shift Code" name="groupby_shift" domain="[]" context="{'group_by':'shift_code'}"/>
Unfortunately, v11 only filters by month, good to know. Anyway, I'll preserve it

2020-04-25 08:45 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report_xlsx.py
> +def formats():
Done in the next commit

2020-04-25 08:45 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report_xlsx.py
> +        return local_dt
Still missing (1) issue with datetimes around midnight

2020-04-25 08:49 UTC, dalonsod commented
Changes and improvements with new commit:
- reused` formats()` `mdc` addon function
- added physical worksheet default timezone support
- improved (even more) timezone offset calculation

Still pending:
- `i18n` update (my fault)
- issue with dates around midnight

2020-04-25 08:52 UTC, dalonsod commented on mdc_rpt_physical_worksheet/i18n/es.po
> +msgstr "Tipo Fichaje (Entrada/Salida)"
I think the possible options in the field description is no longer required

```suggestion
msgstr "Tipo Fichaje"
```

2020-04-25 09:01 UTC, dalonsod commented on mdc_rpt_physical_worksheet/report/report_xlsx.py
> +        for obj in rpt_physical_worksheet:
In order to fix (1), `obj.worksheet_date` should be recalculated starting each `for` iteration:

```suggestion
        for obj in rpt_physical_worksheet:
            obj_worksheet_date = self.convert_UTC_to_TZ(obj.worksheet_date)
```
Then, replace any `obj.worksheet_date` reference to `obj_worksheet_date`.
If this changed is made, no more UTC to TZ conversions are needed later, e.g. the time conversion below (line 182).
With this change date management becomes fully coherent.
What do you think?

2020-04-27 06:13 UTC, lmiguens-solvos commented on mdc_rpt_physical_worksheet/i18n/es.po
> +msgstr "Tipo Fichaje (Entrada/Salida)"
ok. I´m agree

2020-04-27 06:13 UTC, lmiguens-solvos commented on mdc_rpt_physical_worksheet/report/report_xlsx.py
> +        for obj in rpt_physical_worksheet:
I have a problem with this field. This is fields.Date not fields.Datetime

2020-04-27 16:48 UTC, dalonsod commented
@lmiguens-solvos made #4 
When merged, new `manual_open` and `manual_close` fields will be available for mdc.worksheet model. Anyway, before merged a rebase will be needed, I'll help you with it

2020-04-27 17:03 UTC, lmiguens-solvos commented
> @lmiguens-solvos made #4
> When merged, new `manual_open` and `manual_close` fields will be available for `mdc.worksheet` model. Anyway, before merged a rebase will be needed, I'll help you with it

I´m ready. When you want it...

2020-04-27 17:08 UTC, dalonsod commented
> I´m ready. When you want it...

Well, first #4 needs to be approved and merged...

2020-04-27 17:12 UTC, lmiguens-solvos commented
> > I´m ready. When you want it...
> 
> Well, first #4 needs to be approved and merged...

ok, I will try it

2020-04-28 17:26 UTC, lmiguens-solvos commented on mdc_rpt_physical_worksheet/report/report_xlsx.py
> +        for obj in rpt_physical_worksheet:
I´m use only obj_worksheet_datetime in xlsx, but I'm not sure it's the right thing.
What do we do with worksheet that start today and end tomorrow? 
Right now it doesn't look very good. 
Try report for 02/03/2020 and sift 2. Look at Anwar, Shawaiz...

2020-04-29 10:21 UTC, dalonsod approved these changes
👍 
As soon as other reviewer approves it (I'm not looking at anyone @lromero-solvos XD), I'll squash and merge it

2020-04-29 14:39 UTC, lromero-solvos commented
LGTM

2020-04-29 14:45 UTC, dalonsod commented
> LGTM

I guess that's an approval :D

Commits squashed. Ready to merge!!

2020-04-29 14:45 UTC, merged