[11.0][FIX] mdc: report_agrup_revision
solvosci/manufacture pull request #6
Opened 2020-04-30 14:22 UTC by lmiguens-solvos

Changes made:
- review the grouping of the quality field in the 4 reports (views and excel reports)
- review grouping calculation for field total_yield in RptCumulative view
- add grouping calculation for indices in RptIndicators view
- review ReportRptCumulativeXlsx: fix formula failure, fix grouping calculation for field wquality, put column formats like other reports.
Pending to review:
- the indice calculation for total rows ¿should be weighted average with frozen gross to be the same as in new report?
- the grouping of the quality field is not then same when you calculate fot total rows quality column?

2020-04-30 15:26 UTC, dalonsod requested changes
Only code review. See comments (only important the divide by zero one)

2020-04-30 15:26 UTC, dalonsod commented on mdc/report/report.py
>                      if total_weight > 0:
Prevent dividing by zero

```suggestion
                    if total_weight > 0 and total_gross_weigh > 0:

```

2020-04-30 15:26 UTC, dalonsod commented on mdc/report/report.py
> +        # group_fields = ['quality', 'ind_backs', 'ind_mo', 'ind_crumbs', 'ind_quality','ind_cleaning']
Maybe remove this comment?

2020-04-30 15:26 UTC, dalonsod commented on mdc/report/report.py
> +        # group_fields = ['quality', 'ind_backs', 'ind_mo', 'ind_crumbs', 'ind_quality','ind_cleaning']
Maybe remove this comment?

2020-04-30 15:30 UTC, lmiguens-solvos commented on mdc/report/report.py
>                      if total_weight > 0:
Ok. I think i better put the "if total_gross_weight > 0:" only for total_yield calculate:
                    if total_weight > 0:
                        line['quality'] = quality_weight / total_weight
                    if total_gross_weight > 0:
                        line['total_yield'] = total_yield_weight / total_gross_weight

2020-04-30 15:34 UTC, dalonsod commented on mdc/report/report.py
>                      if total_weight > 0:
I agree

2020-04-30 15:35 UTC, lmiguens-solvos commented on mdc/report/report.py
> +        # group_fields = ['quality', 'ind_backs', 'ind_mo', 'ind_crumbs', 'ind_quality','ind_cleaning']
I put this commet just to indicate this situation, because we have defined for example ind_backs = fields.Float('IND Backs', readonly=True, group_operator='avg') (with group_operator='avg') when it should be calculated in this function and not having group_operator in the field definition. 
This is a comment for me in the future.
If, in the future, we want to see this field in view, we must add in this function the calculation of these fields.

2020-04-30 15:35 UTC, lmiguens-solvos commented on mdc/report/report.py
> +        # group_fields = ['quality', 'ind_backs', 'ind_mo', 'ind_crumbs', 'ind_quality','ind_cleaning']
The same as before

2020-04-30 15:37 UTC, lmiguens-solvos commented on mdc/report/report.py
>                      if total_weight > 0:
Thanks for your suggestion anyway, it made me see an improvement there.

2020-04-30 15:55 UTC, dalonsod commented on mdc/report/report.py
> +        # group_fields = ['quality', 'ind_backs', 'ind_mo', 'ind_crumbs', 'ind_quality','ind_cleaning']
OK

2020-04-30 16:18 UTC, dalonsod commented on mdc/report/report.py
>                      if total_weight > 0:
I think that additional `100` is a deliberated change, isn't it?

2020-04-30 16:26 UTC, lmiguens-solvos commented on mdc/report/report.py
>                      if total_weight > 0:
Yes, When I checked that code at your request, I saw that this value had to be percentage

2020-04-30 16:34 UTC, dalonsod approved these changes
LGTM :+1: 

When approved by @lromero-solvos , I'd squash commits and merge it

2020-04-30 19:43 UTC, lromero-solvos commented on mdc/report/report.py
> +        # group_fields = ['quality', 'ind_backs', 'ind_mo', 'ind_crumbs', 'ind_quality','ind_cleaning']
OK, we need to calculate specific group_operators for indicators only in rpt_indicators on the other reports we need to calculate specific grouping with quality field

2020-05-02 09:32 UTC, dalonsod approved these changes

2020-05-02 09:33 UTC, merged